export { BackTo } from './BackTo'
export * from './Boton'
export * from '../Sections/Game/Input'
export * from './Navbar'
export * from './InputForm'
export * from './WelcomeTitle'
export * from './BurgerButton'
